name: Postman Inwarranty Flow Collection
on:
  push: 
      branches: [main]
  workflow_dispatch: 
  schedule:
    - cron: '00 08 * * *'
    - cron: '00 06 * * *'
    - cron: '30 12 * * 1-5'
jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check checkout Code
        uses: actions/checkout@v6.0.2
      
      - name: Install nodejs
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '24'

      - name: Install npm and newman
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

      - name: Run Collection
        run: |
            newman run "InWarrantyFlow TestData.postman_collection.json" \
            -e "QA.postman_environment.json" \
            -d "TestData.csv" \
            -r cli,htmlextra \
            --reporter-htmlextra-export ./newman/index.html

      - name: Make Report
        if: always()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: newman-html-report
          path: newman/*.html

      - name: Creating Github Page Branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
             github_token: ${{ secrets.GITHUB_TOKEN}}
             publish_dir: ./newman

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v17
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME}}
          passowrd: ${{ secrets.EMAIL_PASSWORD}}
          subject: Phoenix Inwarranty Test Flow execution Notification
          to: way2manpreet90@gmail.com
          from: ${{ secrets.EMAIL_USERNAME}}
          body: |
             Hi,
             Phoenix Inwarranty Flow Tests has been executed.The Report has been published
             and the url is: https://manpreet-90.github.io/Phoenix-Inwarranty-flow/
          
          
        
          
        
       
          
          
      
      

      
